#!/usr/bin/env python3
"""
GLM v16.1: BIDIRECTIONAL SEMANTIC COMPOSITION LAYER (GLM35)
===========================================================
EXPERIMENT ID: GLM-COMPOSITION-v2
STATUS: Operational

This module implements a bidirectional semantic composition layer that takes a 
2-hop undirected CRG subgraph and synthesizes a fluent, cohesive 4-6 sentence 
paragraph using rich discourse templates. This resolves the "silent hub" issue 
where central concepts (like 'energy') only have incoming edges.
"""

from typing import List, Dict, Set, Tuple, Any
from dataclasses import dataclass

@dataclass
class PathMotif:
    pattern_type: str  # "transitive_chain", "shared_target", "dual_property", "identity_elaboration"
    nodes: List[str]
    labels: List[str]
    directions: List[str]

class ParagraphComposer:
    def __init__(self, crg, vocab):
        self.crg = crg
        self.vocab = vocab.words if hasattr(vocab, 'words') else vocab

    def _get_neighbors(self, node: str) -> Dict[str, Tuple[str, str]]:
        """
        Returns a dict of {neighbor: (edge_label, direction)} for 1-hop edges.
        Looks at both outgoing and incoming edges to build an undirected neighborhood.
        """
        neighbors = {}
        s = node.lower()

        # Outgoing edges (s -> dst)
        for edge in self.crg.out.get(s, []):
            neighbors[edge.dst.lower()] = (edge.label, "out")

        # Incoming edges (src -> s)
        for edge in self.crg.into.get(s, []):
            neighbors[edge.src.lower()] = (edge.label, "in")

        return neighbors

    def extract_2_hop_subgraph(self, seed: str) -> Tuple[Dict[str, Tuple[str, str]], List[Tuple[str, str, str, str, str]]]:
        """
        Extracts all 1-hop and 2-hop relationships originating from the seed.
        Returns (1-hop neighbors, list of 2-hop triples with directions).
        """
        s = seed.lower()
        hop1 = self._get_neighbors(s)
        hop2_triples = []

        for h1, (label1, dir1) in hop1.items():
            hop2 = self._get_neighbors(h1)
            for h2, (label2, dir2) in hop2.items():
                if h2 != s:  # Avoid cycling back to seed immediately
                    hop2_triples.append((h1, label2, h2, dir1, dir2))

        return hop1, hop2_triples

    def identify_motifs(self, seed: str, hop1: Dict[str, Tuple[str, str]], hop2: List[Tuple[str, str, str, str, str]]) -> List[PathMotif]:
        """Identifies logical motifs within the 2-hop undirected subgraph."""
        motifs = []
        s = seed.lower()

        # 1. Look for Transitive Chains: Seed <-> H1 <-> H2
        for h1, label2, h2, dir1, dir2 in hop2:
            res1 = hop1.get(h1)
            if res1:
                label1, dir1 = res1
                motifs.append(PathMotif(
                    pattern_type="transitive_chain",
                    nodes=[s, h1, h2],
                    labels=[label1, label2],
                    directions=[dir1, dir2]
                ))

        # 2. Look for Shared Targets: Seed <-> H1 and H2 <-> H1
        for h1, (label1, dir1) in hop1.items():
            for h2, (label2, dir2) in hop1.items():
                if h2 != h1:
                    h2_neighbors = self._get_neighbors(h2)
                    if h1 in h2_neighbors:
                        l2, d2 = h2_neighbors[h1]
                        motifs.append(PathMotif(
                            pattern_type="shared_target",
                            nodes=[s, h2, h1],
                            labels=[label2, l2],
                            directions=[dir2, d2]
                        ))

        return motifs

    def _verbalize_relation(self, src: str, label: str, dst: str, direction: str) -> str:
        """Verbalizes a relation based on its direction."""
        s_cap = src.capitalize()
        d_cap = dst.capitalize()
        l_clean = label.replace('_', ' ')

        if direction == "out":
            return f"{s_cap} {l_clean} {dst}"
        else:
            # Reverse phrasing for incoming edges
            passive_map = {
                "is_a": f"{d_cap} is a category containing {src}",
                "generates": f"{d_cap} is generated by {src}",
                "depends_on": f"{d_cap} depends on {src}",
                "commutes_with": f"{d_cap} commutes with {src}",
                "scales_as": f"{d_cap} scales as {src}",
                "is_dual_to": f"{d_cap} is dual to {src}",
                "measures": f"{d_cap} is measured by {src}",
                "has_property": f"{d_cap} is a property of {src}",
            }
            return passive_map.get(label, f"{d_cap} relates to {src}")

    def compose_paragraph(self, seed: str) -> str:
        """Synthesizes a 4-6 sentence paragraph with discourse structure."""
        s = seed.lower()
        if s not in self.vocab:
            return f"The concept of {seed} remains ungrounded in the active vocabulary."

        hop1, hop2 = self.extract_2_hop_subgraph(s)
        motifs = self.identify_motifs(s, hop1, hop2)

        sentences = []

        # Sentence 1: Grounding/Definition of Seed
        seed_cap = seed.capitalize()
        entry = self.vocab.get(s)
        defn = getattr(entry, 'definition', '') if entry else ''
        if defn:
            first_sentence = defn.split('.')[0] + "."
            sentences.append(first_sentence)
        else:
            sentences.append(f"{seed_cap} represents a fundamental coordinate within the active geometric substrate.")

        # Process Motifs to build the narrative core (Sentences 2-4)
        used_nodes = {s}
        chain_added = False
        shared_added = False

        for m in motifs:
            if len(sentences) >= 5:
                break

            if m.pattern_type == "transitive_chain" and not chain_added:
                n1, n2, n3 = m.nodes[0], m.nodes[1], m.nodes[2]
                l1, l2 = m.labels[0], m.labels[1]
                d1, d2 = m.directions[0], m.directions[1]

                rel1 = self._verbalize_relation(n1, l1, n2, d1)
                rel2 = self._verbalize_relation(n2, l2, n3, d2)

                sentences.append(f"Within this topological framework, {rel1.lower()}.")
                sentences.append(f"As a consequence, {rel2.lower()}, establishing a direct causal pathway.")
                sentences.append(f"Therefore, we can deduce that {n1.capitalize()} indirectly influences {n3} through the mediation of {n2}.")

                used_nodes.update(m.nodes)
                chain_added = True

            elif m.pattern_type == "shared_target" and not shared_added:
                n1, n2, n3 = m.nodes[0], m.nodes[1], m.nodes[2]
                l1, l2 = m.labels[0], m.labels[1]
                d1, d2 = m.directions[0], m.directions[1]

                rel1 = self._verbalize_relation(n1, l1, n3, d1)
                rel2 = self._verbalize_relation(n2, l2, n3, d2)

                sentences.append(f"Crucially, both {n1.capitalize()} and {n2} converge on {n3}.")
                sentences.append(f"While {rel1.lower()}, {rel2.lower()} to stabilize the local manifold.")

                used_nodes.update(m.nodes)
                shared_added = True

        # Fallback if no motifs were found (build a simple descriptive paragraph from 1-hop neighbors)
        if len(sentences) <= 2 and hop1:
            sentences.append(f"The local neighborhood of {s} is highly connected.")
            for h1, (label, direction) in list(hop1.items())[:2]:
                rel = self._verbalize_relation(s, label, h1, direction)
                sentences.append(f"Specifically, {rel.lower()}.")

        # Final Sentence: Substrate Coherence / Verification
        if len(sentences) >= 3:
            sentences.append(f"This multi-hop synthesis anchors the local neighborhood of {seed_cap} with high geometric fidelity.")

        return " ".join(sentences)

if __name__ == '__main__':
    from GLM11_runtime import GLMRuntimeV37
    rt = GLMRuntimeV37()
    composer = ParagraphComposer(rt.crg, rt.vocab_dict)

    print("=== TESTING PARAGRAPH COMPOSER ===")
    test_topics = ["hamiltonian", "energy", "symmetry"]
    for topic in test_topics:
        print(f"\nTopic: {topic.upper()}")
        print("-" * 50)
        print(composer.compose_paragraph(topic))