#!/usr/bin/env python3
"""
GLM EXPANDED CRG — Massively Curated Semantic Relationships
============================================================
This module provides 500+ curated semantic edges for the Concept Relation Graph,
organized by domain. Each edge is a meaningful, human-verifiable relationship.

The edges follow the UBP ontological layer structure:
  - Reality (concrete things) → Information (properties/qualities)
  - Activation (processes/actions) → Potential (abstract relations)

Usage:
    from GLM_CRG_EXPANDED import inject_expanded_crg
    inject_expanded_crg(crg)  # adds all edges to an existing CRG
"""

from typing import List, Tuple

# ══════════════════════════════════════════════════════════════════════════════
# EDGE FORMAT: (source, label, target)
# Labels: is_a, generates, measures, depends_on, commutes_with, scales_as,
#         is_dual_to, has_property, constrains, produces, contains,
#         transforms, mediates, characterizes, quantifies, governs
# ══════════════════════════════════════════════════════════════════════════════

# ── 1. QUANTUM MECHANICS ─────────────────────────────────────────────────────
QUANTUM_MECHANICS = [
    ("hamiltonian", "generates", "time"),
    ("hamiltonian", "governs", "evolution"),
    ("hamiltonian", "determines", "energy"),
    ("hamiltonian", "commutes_with", "momentum"),
    ("wavefunction", "describes", "particle"),
    ("wavefunction", "has_property", "amplitude"),
    ("wavefunction", "depends_on", "time"),
    ("wavefunction", "has_property", "phase"),
    ("observable", "measures", "state"),
    ("observable", "commutes_with", "hamiltonian"),
    ("operator", "generates", "transformation"),
    ("operator", "acts_on", "wavefunction"),
    ("eigenvalue", "characterizes", "observable"),
    ("eigenvalue", "quantifies", "measurement"),
    ("eigenstate", "is_a", "state"),
    ("eigenstate", "has_property", "definite"),
    ("commutator", "measures", "incompatibility"),
    ("commutator", "quantifies", "uncertainty"),
    ("uncertainty", "constrains", "measurement"),
    ("uncertainty", "depends_on", "commutator"),
    ("superposition", "combines", "state"),
    ("superposition", "has_property", "coherence"),
    ("entanglement", "correlates", "particle"),
    ("entanglement", "has_property", "nonlocal"),
    ("measurement", "collapses", "wavefunction"),
    ("measurement", "produces", "eigenvalue"),
    ("hilbert", "contains", "state"),
    ("hilbert", "has_property", "dimension"),
    ("probability", "quantifies", "measurement"),
    ("probability", "depends_on", "amplitude"),
    ("density", "describes", "ensemble"),
    ("density", "has_property", "trace"),
    ("trace", "quantifies", "density"),
    ("projection", "selects", "state"),
    ("projection", "reduces", "dimension"),
    ("hermitian", "characterizes", "observable"),
    ("unitary", "preserves", "probability"),
    ("unitary", "governs", "evolution"),
    ("symmetry", "generates", "conservation"),
    ("symmetry", "commutes_with", "hamiltonian"),
    ("conservation", "follows", "symmetry"),
    ("conservation", "constrains", "evolution"),
    ("decoherence", "destroys", "superposition"),
    ("decoherence", "produces", "classical"),
    ("tunneling", "enables", "transmission"),
    ("tunneling", "depends_on", "barrier"),
    ("scattering", "measures", "interaction"),
    ("scattering", "produces", "cross"),
    ("cross", "quantifies", "scattering"),
    ("decay", "produces", "particle"),
    ("decay", "depends_on", "coupling"),
    ("lifetime", "quantifies", "decay"),
    ("resonance", "enhances", "scattering"),
    ("resonance", "has_property", "width"),
]

# ── 2. THERMODYNAMICS & STATISTICAL MECHANICS ────────────────────────────────
THERMODYNAMICS = [
    ("entropy", "measures", "disorder"),
    ("entropy", "quantifies", "information"),
    ("entropy", "depends_on", "temperature"),
    ("entropy", "scales_as", "logarithm"),
    ("temperature", "measures", "energy"),
    ("temperature", "governs", "distribution"),
    ("energy", "is_a", "conserved"),
    ("energy", "generates", "motion"),
    ("energy", "transforms", "state"),
    ("heat", "transfers", "energy"),
    ("heat", "flows", "temperature"),
    ("work", "transfers", "energy"),
    ("work", "produces", "force"),
    ("pressure", "measures", "force"),
    ("pressure", "depends_on", "temperature"),
    ("volume", "constrains", "pressure"),
    ("free", "determines", "equilibrium"),
    ("free", "combines", "energy"),
    ("equilibrium", "minimizes", "free"),
    ("equilibrium", "has_property", "detailed"),
    ("partition", "generates", "thermodynamics"),
    ("partition", "quantifies", "state"),
    ("boltzmann", "relates", "entropy"),
    ("boltzmann", "quantifies", "probability"),
    ("gibbs", "measures", "free"),
    ("helmholtz", "measures", "free"),
    ("chemical", "drives", "reaction"),
    ("chemical", "depends_on", "concentration"),
    ("fugacity", "quantifies", "chemical"),
    ("activity", "measures", "chemical"),
    ("phase", "describes", "matter"),
    ("phase", "transitions", "temperature"),
    ("critical", "characterizes", "phase"),
    ("latent", "quantifies", "phase"),
    ("fluctuation", "measures", "deviation"),
    ("fluctuation", "depends_on", "temperature"),
    ("dissipation", "destroys", "energy"),
    ("dissipation", "produces", "entropy"),
    ("irreversibility", "characterizes", "process"),
    ("irreversibility", "increases", "entropy"),
    ("carnot", "limits", "efficiency"),
    ("efficiency", "quantifies", "conversion"),
    ("adiabatic", "preserves", "entropy"),
    ("isothermal", "preserves", "temperature"),
    ("isobaric", "preserves", "pressure"),
]

# ── 3. ELECTROMAGNETISM ──────────────────────────────────────────────────────
ELECTROMAGNETISM = [
    ("electric", "generates", "field"),
    ("electric", "produces", "force"),
    ("magnetic", "generates", "field"),
    ("magnetic", "deflects", "charge"),
    ("charge", "sources", "field"),
    ("charge", "is_a", "conserved"),
    ("current", "generates", "magnetic"),
    ("current", "depends_on", "charge"),
    ("voltage", "drives", "current"),
    ("voltage", "measures", "energy"),
    ("resistance", "opposes", "current"),
    ("resistance", "dissipates", "energy"),
    ("capacitance", "stores", "charge"),
    ("capacitance", "stores", "energy"),
    ("inductance", "stores", "magnetic"),
    ("inductance", "opposes", "current"),
    ("impedance", "opposes", "alternating"),
    ("impedance", "combines", "resistance"),
    ("conductivity", "quantifies", "conduction"),
    ("permittivity", "characterizes", "dielectric"),
    ("permeability", "characterizes", "magnetic"),
    ("flux", "measures", "field"),
    ("flux", "quantifies", "penetration"),
    ("faraday", "governs", "induction"),
    ("faraday", "relates", "electric"),
    ("ampere", "governs", "current"),
    ("gauss", "measures", "magnetic"),
    ("lorentz", "governs", "force"),
    ("lorentz", "combines", "electric"),
    ("maxwell", "unifies", "electric"),
    ("maxwell", "governs", "field"),
    ("poynting", "quantifies", "energy"),
    ("poynting", "describes", "radiation"),
    ("radiation", "emits", "energy"),
    ("radiation", "propagates", "wave"),
    ("wave", "carries", "energy"),
    ("wave", "has_property", "frequency"),
    ("frequency", "quantifies", "oscillation"),
    ("wavelength", "inverses", "frequency"),
    ("polarization", "characterizes", "wave"),
    ("reflection", "preserves", "energy"),
    ("refraction", "bends", "wave"),
    ("diffraction", "spreads", "wave"),
    ("interference", "combines", "wave"),
    ("interference", "produces", "pattern"),
]

# ── 4. RELATIVITY ────────────────────────────────────────────────────────────
RELATIVITY = [
    ("spacetime", "contains", "event"),
    ("spacetime", "has_property", "curvature"),
    ("curvature", "describes", "spacetime"),
    ("curvature", "depends_on", "energy"),
    ("metric", "quantifies", "distance"),
    ("metric", "describes", "geometry"),
    ("geodesic", "minimizes", "distance"),
    ("geodesic", "describes", "motion"),
    ("tensor", "generalizes", "vector"),
    ("tensor", "describes", "curvature"),
    ("einstein", "relates", "curvature"),
    ("einstein", "unifies", "spacetime"),
    ("gravity", "curves", "spacetime"),
    ("gravity", "attracts", "mass"),
    ("mass", "sources", "gravity"),
    ("mass", "has_property", "inertia"),
    ("momentum", "conserves", "motion"),
    ("momentum", "depends_on", "mass"),
    ("angular", "conserves", "rotation"),
    ("angular", "depends_on", "momentum"),
    ("lorentz", "transforms", "coordinate"),
    ("lorentz", "preserves", "interval"),
    ("interval", "measures", "spacetime"),
    ("interval", "is_a", "invariant"),
    ("time", "dilates", "velocity"),
    ("time", "dilates", "gravity"),
    ("length", "contracts", "velocity"),
    ("redshift", "measures", "expansion"),
    ("redshift", "quantifies", "gravity"),
    ("black", "contains", "singularity"),
    ("black", "has_property", "horizon"),
    ("horizon", "bounds", "causality"),
    ("horizon", "has_property", "area"),
    ("hawking", "emits", "radiation"),
    ("hawking", "depends_on", "gravity"),
    ("singularity", "violates", "physics"),
    ("gravitational", "carries", "wave"),
    ("gravitational", "emits", "energy"),
    ("frame", "describes", "observer"),
    ("frame", "has_property", "local"),
    ("equivalence", "relates", "gravity"),
    ("equivalence", "unifies", "inertial"),
    ("cosmological", "drives", "expansion"),
    ("cosmological", "has_property", "constant"),
    ("expansion", "stretches", "spacetime"),
    ("expansion", "depends_on", "energy"),
    ("hubble", "measures", "expansion"),
    ("hubble", "quantifies", "velocity"),
]

# ── 5. PARTICLE PHYSICS ──────────────────────────────────────────────────────
PARTICLE_PHYSICS = [
    ("quark", "is_a", "particle"),
    ("quark", "has_property", "color"),
    ("quark", "generates", "hadron"),
    ("lepton", "is_a", "particle"),
    ("lepton", "has_property", "flavor"),
    ("neutrino", "is_a", "lepton"),
    ("neutrino", "has_property", "mass"),
    ("electron", "is_a", "lepton"),
    ("electron", "has_property", "charge"),
    ("muon", "is_a", "lepton"),
    ("muon", "decays", "electron"),
    ("tau", "is_a", "lepton"),
    ("tau", "decays", "muon"),
    ("proton", "contains", "quark"),
    ("proton", "has_property", "charge"),
    ("neutron", "contains", "quark"),
    ("neutron", "has_property", "neutral"),
    ("meson", "contains", "quark"),
    ("baryon", "contains", "quark"),
    ("gluon", "mediates", "strong"),
    ("gluon", "has_property", "color"),
    ("photon", "mediates", "electromagnetic"),
    ("photon", "has_property", "massless"),
    ("boson", "mediates", "force"),
    ("boson", "has_property", "integer"),
    ("fermion", "has_property", "half"),
    ("fermion", "obeys", "exclusion"),
    ("higgs", "generates", "mass"),
    ("higgs", "has_property", "scalar"),
    ("w", "mediates", "weak"),
    ("w", "decays", "lepton"),
    ("z", "mediates", "weak"),
    ("z", "has_property", "neutral"),
    ("strong", "binds", "quark"),
    ("strong", "generates", "confinement"),
    ("weak", "mediates", "decay"),
    ("weak", "violates", "parity"),
    ("color", "charges", "strong"),
    ("color", "is_a", "quantum"),
    ("flavor", "characterizes", "quark"),
    ("isospin", "characterizes", "nucleon"),
    ("strangeness", "characterizes", "quark"),
    ("chirality", "characterizes", "fermion"),
    ("helicity", "measures", "spin"),
    ("spin", "has_property", "angular"),
    ("spin", "determines", "statistics"),
    ("antiparticle", "is_dual_to", "particle"),
    ("antiparticle", "annihilates", "particle"),
    ("annihilation", "converts", "mass"),
    ("pair", "creates", "particle"),
    ("coupling", "quantifies", "interaction"),
    ("coupling", "depends_on", "energy"),
    ("renormalization", "removes", "divergence"),
    ("renormalization", "scales", "coupling"),
    ("running", "describes", "coupling"),
    ("running", "depends_on", "energy"),
    ("symmetry", "generates", "current"),
    ("current", "conserves", "charge"),
    ("noether", "relates", "symmetry"),
    ("noether", "generates", "conservation"),
    ("gauge", "generates", "force"),
    ("gauge", "requires", "boson"),
    ("lagrangian", "generates", "dynamics"),
    ("lagrangian", "determines", "equation"),
    ("action", "minimizes", "lagrangian"),
    ("action", "generates", "equation"),
    ("feynman", "computes", "amplitude"),
    ("feynman", "sums", "path"),
    ("path", "integrates", "amplitude"),
    ("path", "sums", "history"),
    ("s_matrix", "measures", "scattering"),
    ("s_matrix", "encodes", "interaction"),
    ("cross", "measures", "probability"),
    ("cross", "depends_on", "energy"),
    ("decay", "produces", "particle"),
    ("decay", "depends_on", "coupling"),
    ("lifetime", "quantifies", "stability"),
    ("width", "quantifies", "resonance"),
    ("width", "inverses", "lifetime"),
]

# ── 6. CONDENSED MATTER ──────────────────────────────────────────────────────
CONDENSED_MATTER = [
    ("crystal", "has_property", "lattice"),
    ("crystal", "exhibits", "periodicity"),
    ("lattice", "describes", "crystal"),
    ("lattice", "has_property", "reciprocal"),
    ("phonon", "is_a", "excitation"),
    ("phonon", "carries", "sound"),
    ("phonon", "has_property", "dispersion"),
    ("magnon", "is_a", "excitation"),
    ("magnon", "carries", "spin"),
    ("electron", "carries", "current"),
    ("electron", "has_property", "band"),
    ("band", "determines", "conductivity"),
    ("band", "separates", "energy"),
    ("fermi", "characterizes", "electron"),
    ("fermi", "determines", "occupation"),
    ("gap", "separates", "band"),
    ("gap", "determines", "insulator"),
    ("conductor", "has_property", "metallic"),
    ("insulator", "has_property", "gap"),
    ("semiconductor", "has_property", "small"),
    ("superconductor", "has_property", "zero"),
    ("superconductor", "exhibits", "meissner"),
    ("cooper", "pairs", "electron"),
    ("cooper", "enables", "superconductivity"),
    ("bcs", "explains", "superconductivity"),
    ("bose", "condenses", "particle"),
    ("condensate", "has_property", "macroscopic"),
    ("condensate", "exhibits", "coherence"),
    ("magnetization", "measures", "magnetic"),
    ("magnetization", "orders", "spin"),
    ("ferromagnet", "exhibits", "magnetization"),
    ("antiferromagnet", "alternates", "spin"),
    ("ordering", "reduces", "symmetry"),
    ("ordering", "generates", "excitation"),
    ("disorder", "localizes", "electron"),
    ("disorder", "increases", "resistance"),
    ("anderson", "localizes", "electron"),
    ("mobility", "quantifies", "conduction"),
    ("mobility", "depends_on", "scattering"),
    ("hall", "measures", "carrier"),
    ("quantum", "quantizes", "hall"),
    ("topological", "protects", "state"),
    ("topological", "has_property", "invariant"),
    ("edge", "appears", "boundary"),
    ("edge", "has_property", "chiral"),
    ("majorana", "is_a", "fermion"),
    ("majorana", "is_dual_to", "itself"),
    ("defect", "breaks", "periodicity"),
    ("defect", "creates", "state"),
    ("impurity", "scatters", "electron"),
    ("impurity", "creates", "bound"),
]

# ── 7. MATHEMATICS ───────────────────────────────────────────────────────────
MATHEMATICS = [
    ("derivative", "measures", "rate"),
    ("derivative", "quantifies", "change"),
    ("integral", "accumulates", "area"),
    ("integral", "reverses", "derivative"),
    ("differential", "governs", "evolution"),
    ("differential", "describes", "system"),
    ("matrix", "represents", "transformation"),
    ("matrix", "acts_on", "vector"),
    ("vector", "has_property", "direction"),
    ("vector", "has_property", "magnitude"),
    ("eigenvalue", "characterizes", "matrix"),
    ("eigenvector", "is_a", "vector"),
    ("eigenvector", "preserves", "direction"),
    ("determinant", "measures", "scaling"),
    ("determinant", "quantifies", "invertibility"),
    ("trace", "measures", "sum"),
    ("trace", "is_a", "invariant"),
    ("rank", "measures", "dimension"),
    ("rank", "quantifies", "independence"),
    ("kernel", "measures", "nullity"),
    ("kernel", "contains", "solution"),
    ("norm", "measures", "length"),
    ("norm", "quantifies", "size"),
    ("inner", "measures", "angle"),
    ("inner", "quantifies", "projection"),
    ("tensor", "generalizes", "matrix"),
    ("tensor", "describes", "multilinear"),
    ("manifold", "generalizes", "surface"),
    ("manifold", "has_property", "dimension"),
    ("topology", "studies", "continuity"),
    ("topology", "preserves", "connectedness"),
    ("group", "describes", "symmetry"),
    ("group", "has_property", "closure"),
    ("ring", "generalizes", "integer"),
    ("field", "generalizes", "rational"),
    ("category", "abstracts", "structure"),
    ("functor", "maps", "category"),
    ("homomorphism", "preserves", "structure"),
    ("isomorphism", "preserves", "identity"),
    ("homeomorphism", "preserves", "topology"),
    ("probability", "quantifies", "likelihood"),
    ("probability", "measures", "event"),
    ("distribution", "describes", "random"),
    ("expectation", "measures", "average"),
    ("variance", "measures", "spread"),
    ("covariance", "measures", "correlation"),
    ("gaussian", "describes", "normal"),
    ("poisson", "describes", "rare"),
    ("markov", "describes", "memoryless"),
    ("ergodic", "equates", "time"),
    ("limit", "defines", "convergence"),
    ("series", "sums", "sequence"),
    ("convergence", "approaches", "limit"),
    ("divergence", "departs", "limit"),
    ("continuity", "preserves", "limit"),
    ("compactness", "generalizes", "finite"),
    ("connectedness", "prevents", "separation"),
    ("metric", "quantifies", "distance"),
    ("cauchy", "characterizes", "convergence"),
    ("weierstrass", "guarantees", "extremum"),
    ("fourier", "decomposes", "frequency"),
    ("fourier", "transforms", "signal"),
    ("laplace", "transforms", "differential"),
    ("z_transform", "transforms", "discrete"),
    ("convolution", "combines", "signal"),
    ("correlation", "measures", "similarity"),
]

# ── 8. INFORMATION THEORY & COMPUTATION ──────────────────────────────────────
INFORMATION = [
    ("bit", "quantifies", "information"),
    ("bit", "is_a", "unit"),
    ("entropy", "measures", "information"),
    ("entropy", "quantifies", "uncertainty"),
    ("channel", "carries", "information"),
    ("channel", "has_property", "capacity"),
    ("capacity", "limits", "rate"),
    ("capacity", "depends_on", "bandwidth"),
    ("coding", "compresses", "information"),
    ("coding", "corrects", "error"),
    ("redundancy", "protects", "information"),
    ("redundancy", "costs", "bandwidth"),
    ("shannon", "quantifies", "information"),
    ("shannon", "limits", "capacity"),
    ("algorithm", "solves", "problem"),
    ("algorithm", "has_property", "complexity"),
    ("complexity", "measures", "resource"),
    ("complexity", "quantifies", "difficulty"),
    ("np", "contains", "problem"),
    ("p", "contains", "problem"),
    ("polynomial", "characterizes", "efficient"),
    ("exponential", "characterizes", "hard"),
    ("turing", "computes", "function"),
    ("turing", "defines", "computability"),
    ("automaton", "recognizes", "language"),
    ("grammar", "generates", "language"),
    ("language", "is_a", "set"),
    ("language", "has_property", "recursive"),
    ("logic", "formalizes", "reasoning"),
    ("logic", "has_property", "complete"),
    ("proof", "establishes", "truth"),
    ("proof", "derives", "theorem"),
    ("theorem", "states", "result"),
    ("axiom", "assumes", "truth"),
    ("inference", "derives", "conclusion"),
    ("deduction", "guarantees", "truth"),
    ("induction", "generalizes", "pattern"),
    ("abduction", "infers", "explanation"),
]

# ── 9. COSMOLOGY ─────────────────────────────────────────────────────────────
COSMOLOGY = [
    ("universe", "contains", "matter"),
    ("universe", "has_property", "age"),
    ("universe", "exhibits", "expansion"),
    ("big", "created", "universe"),
    ("big", "produces", "radiation"),
    ("cosmic", "pervades", "universe"),
    ("cosmic", "has_property", "temperature"),
    ("cmb", "is_a", "radiation"),
    ("cmb", "records", "epoch"),
    ("inflation", "stretched", "spacetime"),
    ("inflation", "produces", "perturbation"),
    ("perturbation", "seeded", "structure"),
    ("perturbation", "grew", "gravity"),
    ("dark", "dominates", "matter"),
    ("dark", "has_property", "invisible"),
    ("dark", "drives", "expansion"),
    ("matter", "clusters", "gravity"),
    ("matter", "has_property", "density"),
    ("baryon", "is_a", "matter"),
    ("baryon", "forms", "structure"),
    ("galaxy", "contains", "star"),
    ("galaxy", "clusters", "gravity"),
    ("star", "generates", "fusion"),
    ("star", "emits", "light"),
    ("fusion", "combines", "nucleus"),
    ("fusion", "produces", "energy"),
    ("supernova", "destroys", "star"),
    ("supernova", "produces", "element"),
    ("neutron", "is_a", "remnant"),
    ("pulsar", "emits", "radiation"),
    ("pulsar", "rotates", "rapidly"),
    ("quasar", "emits", "energy"),
    ("quasar", "has_property", "luminosity"),
    ("luminosity", "measures", "power"),
    ("magnitude", "measures", "brightness"),
    ("distance", "measures", "separation"),
    ("parallax", "measures", "distance"),
    ("redshift", "measures", "velocity"),
    ("blueshift", "measures", "approach"),
    ("singularity", "marks", "boundary"),
    ("horizon", "bounds", "observability"),
    ("curvature", "determines", "geometry"),
    ("flat", "has_property", "zero"),
    ("open", "has_property", "negative"),
    ("closed", "has_property", "positive"),
    ("omega", "quantifies", "density"),
    ("cosmological", "drives", "acceleration"),
    ("de_sitter", "describes", "expansion"),
    ("friedmann", "governs", "expansion"),
    ("lemaitre", "predicts", "expansion"),
    ("hubble", "measures", "expansion"),
    ("habble", "quantifies", "constant"),
    ("dark", "accelerates", "expansion"),
    ("dark", "has_property", "negative"),
]

# ── 10. UBP-SPECIFIC CONCEPTS ────────────────────────────────────────────────
UBP_SPECIFIC = [
    ("golay", "corrects", "error"),
    ("golay", "has_property", "perfect"),
    ("golay", "encodes", "bit"),
    ("leech", "packs", "sphere"),
    ("leech", "has_property", "kissing"),
    ("leech", "achieves", "density"),
    ("nrci", "measures", "coherence"),
    ("nrci", "quantifies", "stability"),
    ("octad", "is_a", "codeword"),
    ("octad", "has_property", "weight"),
    ("codeword", "is_a", "vector"),
    ("codeword", "has_property", "syndrome"),
    ("syndrome", "detects", "error"),
    ("syndrome", "locates", "error"),
    ("hamming", "measures", "distance"),
    ("hamming", "quantifies", "difference"),
    ("syntropy", "opposes", "entropy"),
    ("syntropy", "generates", "order"),
    ("monad", "combines", "pi"),
    ("monad", "has_property", "triadic"),
    ("wobble", "measures", "entropy"),
    ("wobble", "depends_on", "monad"),
    ("observer", "measures", "system"),
    ("observer", "has_property", "constant"),
    ("substrate", "contains", "information"),
    ("substrate", "has_property", "dimension"),
    ("geometry", "encodes", "meaning"),
    ("geometry", "constrains", "physics"),
    ("lattice", "grounds", "computation"),
    ("lattice", "provides", "structure"),
    ("codeword", "represents", "concept"),
    ("codeword", "has_property", "stability"),
    ("tax", "measures", "symmetry"),
    ("tax", "quantifies", "cost"),
    ("fold", "reduces", "dimension"),
    ("fold", "preserves", "structure"),
    ("sextet", "partitions", "coordinate"),
    ("sextet", "encodes", "layer"),
    ("layer", "determines", "grammar"),
    ("layer", "classifies", "concept"),
    ("reality", "contains", "noun"),
    ("information", "contains", "adjective"),
    ("activation", "contains", "verb"),
    ("potential", "contains", "operator"),
    ("crystallization", "produces", "thesis"),
    ("crystallization", "requires", "evidence"),
    ("coherence", "measures", "consistency"),
    ("coherence", "quantifies", "agreement"),
    ("zone", "accumulates", "evidence"),
    ("zone", "has_property", "centroid"),
    ("centroid", "represents", "average"),
    ("centroid", "evolves", "evidence"),
]

# ── 11. CROSS-DOMAIN BRIDGES ─────────────────────────────────────────────────
CROSS_DOMAIN = [
    ("entropy", "connects", "thermodynamics"),
    ("entropy", "connects", "information"),
    ("symmetry", "governs", "physics"),
    ("symmetry", "governs", "mathematics"),
    ("energy", "appears", "mechanics"),
    ("energy", "appears", "electromagnetism"),
    ("energy", "appears", "relativity"),
    ("conservation", "follows", "symmetry"),
    ("conservation", "constrains", "dynamics"),
    ("duality", "relates", "theory"),
    ("duality", "maps", "description"),
    ("renormalization", "appears", "quantum"),
    ("renormalization", "appears", "statistical"),
    ("universality", "emerges", "critical"),
    ("universality", "characterizes", "phase"),
    ("scaling", "describes", "behavior"),
    ("scaling", "governs", "critical"),
    ("dimension", "appears", "geometry"),
    ("dimension", "appears", "physics"),
    ("dimension", "appears", "information"),
    ("topology", "appears", "mathematics"),
    ("topology", "appears", "physics"),
    ("topology", "appears", "computation"),
    ("invariance", "characterizes", "symmetry"),
    ("invariance", "preserves", "law"),
    ("covariance", "generalizes", "invariance"),
    ("covariance", "preserves", "form"),
    ("action", "generates", "equation"),
    ("action", "appears", "mechanics"),
    ("action", "appears", "field"),
    ("lagrangian", "generates", "action"),
    ("lagrangian", "appears", "particle"),
    ("lagrangian", "appears", "field"),
    ("hamiltonian", "generates", "evolution"),
    ("hamiltonian", "appears", "quantum"),
    ("hamiltonian", "appears", "statistical"),
    ("partition", "generates", "thermodynamics"),
    ("partition", "encodes", "state"),
    ("path", "integrates", "amplitude"),
    ("path", "sums", "history"),
    ("group", "describes", "symmetry"),
    ("group", "appears", "physics"),
    ("group", "appears", "geometry"),
    ("representation", "implements", "group"),
    ("representation", "maps", "matrix"),
    ("gauge", "generates", "force"),
    ("gauge", "requires", "boson"),
    ("gauge", "appears", "electromagnetism"),
    ("gauge", "appears", "standard"),
]

# ── 12. GRAVITY & SPACETIME (additional edges) ───────────────────────────────
GRAVITY_EXTRA = [
    ("gravity", "curves", "spacetime"),
    ("gravity", "attracts", "mass"),
    ("gravity", "governs", "orbit"),
    ("gravity", "produces", "tidal"),
    ("gravity", "bends", "light"),
    ("gravity", "redshifts", "frequency"),
    ("gravity", "delays", "time"),
    ("gravity", "waves", "spacetime"),
    ("spacetime", "curved_by", "gravity"),
    ("mass", "generates", "gravity"),
    ("curvature", "caused_by", "mass"),
    ("einstein", "equation", "gravity"),
    ("einstein", "predicted", "waves"),
    ("black", "creates", "gravity"),
    ("orbit", "governed_by", "gravity"),
    ("tide", "caused_by", "gravity"),
]

# ══════════════════════════════════════════════════════════════════════════════
# AGGREGATE
# ══════════════════════════════════════════════════════════════════════════════

ALL_EDGES: List[Tuple[str, str, str]] = (
    QUANTUM_MECHANICS
    + THERMODYNAMICS
    + ELECTROMAGNETISM
    + RELATIVITY
    + PARTICLE_PHYSICS
    + CONDENSED_MATTER
    + MATHEMATICS
    + INFORMATION
    + COSMOLOGY
    + UBP_SPECIFIC
    + CROSS_DOMAIN
    + GRAVITY_EXTRA
)


def inject_expanded_crg(crg) -> int:
    """Inject all expanded edges into an existing CRG.
    
    Returns the number of edges added (skips duplicates).
    """
    existing = set()
    for e in crg.edges:
        existing.add((e.src, e.label, e.dst))
    
    added = 0
    for src, label, dst in ALL_EDGES:
        key = (src, label, dst)
        if key not in existing:
            crg.add_edge(src, label, dst)
            existing.add(key)
            added += 1
    
    return added


def get_domain_edges(domain: str) -> List[Tuple[str, str, str]]:
    """Get edges for a specific domain."""
    domain_map = {
        "quantum": QUANTUM_MECHANICS,
        "thermodynamics": THERMODYNAMICS,
        "electromagnetism": ELECTROMAGNETISM,
        "relativity": RELATIVITY,
        "particle": PARTICLE_PHYSICS,
        "condensed": CONDENSED_MATTER,
        "mathematics": MATHEMATICS,
        "information": INFORMATION,
        "cosmology": COSMOLOGY,
        "ubp": UBP_SPECIFIC,
        "cross": CROSS_DOMAIN,
    }
    return domain_map.get(domain.lower(), [])


def edge_count() -> int:
    """Total number of curated edges."""
    return len(ALL_EDGES)


if __name__ == "__main__":
    print(f"Expanded CRG: {len(ALL_EDGES)} curated edges across 11 domains")
    print(f"  Quantum Mechanics: {len(QUANTUM_MECHANICS)}")
    print(f"  Thermodynamics: {len(THERMODYNAMICS)}")
    print(f"  Electromagnetism: {len(ELECTROMAGNETISM)}")
    print(f"  Relativity: {len(RELATIVITY)}")
    print(f"  Particle Physics: {len(PARTICLE_PHYSICS)}")
    print(f"  Condensed Matter: {len(CONDENSED_MATTER)}")
    print(f"  Mathematics: {len(MATHEMATICS)}")
    print(f"  Information Theory: {len(INFORMATION)}")
    print(f"  Cosmology: {len(COSMOLOGY)}")
    print(f"  UBP-Specific: {len(UBP_SPECIFIC)}")
    print(f"  Cross-Domain: {len(CROSS_DOMAIN)}")
